"""Write a Markdown report for a CSV file. Bundled with the csv-report skill.

Usage:
    python3 csv_report.py FILE.csv --group-by COLUMN --amount COLUMN [--out DIR]
"""

import argparse
import csv
import os
from collections import defaultdict


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("csv_path")
    parser.add_argument("--group-by", required=True)
    parser.add_argument("--amount", required=True)
    parser.add_argument("--out", default="/workspace/reports")
    args = parser.parse_args()

    totals: dict[str, float] = defaultdict(float)
    counts: dict[str, int] = defaultdict(int)
    rows = 0
    largest: tuple[str, float] | None = None

    with open(args.csv_path, newline="") as f:
        for row in csv.DictReader(f):
            rows += 1
            group = row[args.group_by]
            amount = float(row[args.amount])
            totals[group] += amount
            counts[group] += 1
            first_col = next(iter(row.values()))
            if largest is None or amount > largest[1]:
                largest = (first_col, amount)

    ranked = sorted(totals.items(), key=lambda kv: kv[1], reverse=True)
    name = os.path.splitext(os.path.basename(args.csv_path))[0]

    lines = [
        f"# Report: {name}",
        "",
        f"- Source: `{args.csv_path}`",
        f"- Rows: {rows:,}",
        f"- Largest {args.amount}: {largest[1]:.2f} EUR (row {largest[0]})" if largest else "- Largest: n/a",
        "",
        f"## Total {args.amount} by {args.group_by}",
        "",
        f"| {args.group_by} | rows | total |",
        "|---|---:|---:|",
    ]
    lines += [f"| {g} | {counts[g]:,} | {t:.2f} EUR |" for g, t in ranked]
    lines += ["", "Generated by csv-report skill"]

    os.makedirs(args.out, exist_ok=True)
    out_path = os.path.join(args.out, f"{name}.md")
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    top = f"{ranked[0][0]} ({ranked[0][1]:.2f} EUR)" if ranked else "n/a"
    print(f"report={out_path} rows={rows} top_{args.group_by}={top}")


if __name__ == "__main__":
    main()
